### ISSUE TITLE
Improve discovery of node.js/mean azure images that are available for creating a VM

### ISSUE THREAD

**Issue by nicolehaugen** [lostintangent/node-e2e-nina2016#24]
In order to discover the Azure images available for creating a VM for use with the node.js/MEAN stack, there are 3 main paths:

1.) Use the [Azure Marketplace portal](https://azure.microsoft.com/en-us/develop/nodejs/)
2.) Or, use the Azure portal to start creating a new VM and search through available images
3.) Or, use the Azure CLI to list available images (az vm image list -all)

In all cases, the discovery of relevant images could be improved - currently, the user must weed their way through information in order to find node.js/mean images.

Here's more details on the experience of each one and how they could be improved:

* Azure Marketplace portal
There is a link to this from the Node.js Developer Center page that automatically applies a filter of "node.js" on it - however, there are 42 results to sift through.  Many of the options listed don't appear to be relevant, or at least, their relevance isn't clear.  It would be nice to try and categorize these better so that all of the directly relevant images to node and MEAN are at the top, with related images in separate categories (such as by database, OS, etc).  And, if there are unrelated images, don't show them at all.

* Azure Portal
When you choose to start creating a new VM, you are presented with categorized images which helps - but by default, there aren't any node.js or MEAN related images shown on the primary VM creation page.  To find them you must drill down into each category or do a search which is easy to do, but, with Node.JS being a priority, maybe at least one category (such as Application Infrastructure) should have a Node.JS/MEAN related image shown?  Even better would be if the portal could be smarter in terms of the developer's preferences and show by default which images are most relevant to them. (see screenshot below)

* Azure CLI
From the command line, you can get a list of all available images, but the naming scheme is a mystery and I wasn't able to map these names back to the images that I saw through the Azure Portal or Azure marketplace - I don't feel that users will be successful using the Azure CLI for the purpose of discovering which images are available unless better aliases are provided as mentioned here in [this issue](https://github.com/Azure/azure-cli/issues/2349).  Assuming this issue gets fixed, we should also provide tips in the walk through on how to query for the list of available node.js/mean related images through the CLI to make this more intuitive.

Here's screenshot of azure portal experience: 
![image](https://cloud.githubusercontent.com/assets/10600161/23967721/086fc4b6-098e-11e7-957a-29f4ee1df3da.png)

**Comment by lostintangent** [comment]
Agreed! Besides discoverability, the Az CLI doesn't even currently allow you to provision most VM images, due to an issue with 3rd party marketplace VMs. So the CLI workflow in general is currently not optimized for VM usage.

For #2, I just sent an e-mail to see about getting the Node.js VM added to this "featured" page, since as you mentioned, we should be prioritizing its visibility.

For #1, I actually only see [7 results](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/category/compute?operatingSystem=acom-linux&search=node.js), which seem pretty relevant. Let the page load for a second. It seems like it loads a long list, and then updates to only show 7.

In addition, I recently updated the azure.com/node page to ensure the `Featured Node.js stacks on Azure` list only includes 4 VMs, which are the ones we want to draw attention to. I have a request out to replace the `Let's Chat` VM with the `N|Solid` one, at which point, we'd draw attention to the Bitnami Mean and Node.js images, N|Solid, and the Mean.io image, which I think is the right list.

**Comment by nicolehaugen** [comment]
Glad to hear that #3 and #2 scenarios will be improved.

For #1, you're right...I do see 7 results now.  I'm not sure why I was seeing so many before.

**Comment by lostintangent** [comment]
The change to add N|Solid to the list of featured VMs on the dev center was made live today, so in general, I think that gives us a good curated story for Node.js VMs from the dev center. We still need to improve the content on the dev center to be more clear, but as far as pointing users at something, we should be able to use that page.

![image](https://cloud.githubusercontent.com/assets/116461/24225649/de56b43c-0f1e-11e7-953d-783513d49a36.png)

I spoke with the Azure marketplace team, and it's not going to be straight forward to get a Node.js VM featured in the Azure portal, so that's not going to be an avenue we can pursue in the near term.

That said, the search results look good from the marketplace and portal, and our dev center has the right list of images, so I'm thinking that's sufficient for now. The "getting started" doc that we'll have for VMs can also point at the right images in order to ensure folks can be successful.

**Comment by lostintangent** [comment]
I removed the second MEAN VM from the Node dev center page, which keeps the list of prescribed VM images for Node to just three. We're also dramatically simplifying that page, which will help allow us to drive traffic to it, and use it as the point of discoverability for Node VMs.

As we discussed previously, it isn't straightforward to update the list of feature VMs in the Azure portal, so I'm going to close this issue for now, and we'll use the Node dev center page to drive the awareness for VMs we expect devs to need.
