### ISSUE TITLE
Walkthru of local git deployment to App Service results in deployment failure and 403 forbidden error

### ISSUE THREAD

**Issue by nicolehaugen** [lostintangent/node-e2e-nina2016#26]
The steps described in this [walkthru ](https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-nodejs)result in a deployment error occurring - specifically the issue is in step #5 where the version of node is changed.  If you leave the version of node left set to the default, the app successfully deploys.

This is likely a bug in the deployment script, but more follow up is needed to confirm this.  There is also a question of whether the NPM version should be configurable.

Refer to this email for further details.
	
[DeploymentError.docx.docx](https://github.com/lostintangent/node-e2e-nina2016/files/851722/DeploymentError.docx.docx)

**Comment by lostintangent** [comment]
@nicolehaugen79 Thanks for reporting this! I just sent a mail to the App Service PM (with you on it), so we can hopefully track this issue down. In the meantime, I wonder whether we shouldn't [update that walkthrough](https://github.com/Microsoft/azure-docs/blob/master/articles/app-service-web/app-service-web-get-started-nodejs.md) to remove step #5? If it makes the demo work, that's awesome, since it also simplifies it as well :)

Regarding the question about allowing the NPM version o be configurable. That may be valuable, but I'd prefer not to expect/require users to do it, since the default NPM version that comes along with a specific Node.js version has been tested for compatibility. My hunch here is that the deployment scripts don't handle requests for Node versions that aren't actually available. But we'll see what details come out.

**Comment by nicolehaugen** [comment]
Thanks for starting the thread with the PM - I have logged [this issue](https://github.com/lostintangent/node-e2e-nina2016/issues/26) so that we can track the bug with node version 6.9.3 not currently being supported by the deploy script.

And then also logged this issue that tracks the 403 Forbidden error that occurs if the user fails to set the default node version (this only happens for Linux when using the Azure CLI): https://github.com/Azure-App-Service/kudu/issues/11

As for NPM, I'll wait on that one since I'm not sure whether there is truly user need for that.

**Comment by lostintangent** [comment]
This has been fixed!

**Comment by RoboBurned** [comment]
The issue still exists with node 8.1
